--- #YAML:1.0
name:               DBIx-Class-Result-ProxyField
version:            0.01
abstract:           Component Result::ProxyField is a component for DBIx::Class object which permit to defined public name for each column object
author:
    - Nicolas Oudard <noudard@weborama.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
